### ISSUE TITLE
Gene normalizer don't work

### ISSUE THREAD

**Issue by shipse92** [amalic/bern-docker#1]
I built this docker image and run this image with your command.
Then openned web browser, called like this.
http://localhost:8008/?pmid=30429604&format=pubtator

Result :
30429604	15	19	CD95	gene	CUI-less
30429604	20	29	PLCgamma1	gene	CUI-less
30429604	51	55	Th17	gene	CUI-less
30429604	77	82	CD95L	gene	CUI-less
30429604	110	117	m-CD95L	gene	CUI-less
30429604	138	154	metalloproteases	gene	CUI-less
30429604	184	191	s-CD95L	gene	CUI-less
30429604	201	208	m-CD95L	gene	CUI-less
30429604	230	237	s-CD95L	gene	CUI-less
30429604	242	246	CD95	gene	CUI-less

All Gene ID is CUI-less.
So, I saw the nohup_gene.out, file was logging like this.

nohup_gene.out :
java.io.IOException: Cannot run program "./Ab3P": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:450)
        at java.lang.Runtime.exec(Runtime.java:347)
        at GNormPluslib.GNR.LoadInputFile(GNR.java:72)
        at GNormPluslib.GNormPlus.run(GNormPlus.java:315)
        at GNormPluslib.GNormPlusServer.main(GNormPlusServer.java:35)
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 6 more

How can i do that?

**Comment by amalic** [comment]
?

**Comment by shipse92** [comment]
I mean GNormPlusServer don't work.
permission error occurs.

Can you help me?

**Comment by amalic** [comment]
I would help you if I could. But this repo is only dockerizing Bern, which was originally developed in this [repository](https://github.com/dmis-lab/bern/blob/master/README.md).

I recommend to create a ticket in the Bern repo. 

Please close this ticket and open a new on in case I need to update something here.

**Comment by shipse92** [comment]
I know original repo.
And I used original bern but original didn't occur error like this.

This error occurs only docker environment I think.
How is your result?

**Comment by amalic** [comment]
I just tried your call with my Docker image but with port 80 instead of 8008. And this is the output

URI used: http://localhost/?pmid=30429604&format=pubtator

```
30429604|t|Disrupting the CD95-PLCgamma1 interaction prevents Th17-driven inflammation.
30429604|a|CD95L is a transmembrane ligand (m-CD95L) that is cleaved by metalloproteases to release a soluble ligand (s-CD95L). Unlike m-CD95L, interaction between s-CD95L and CD95 fails to recruit caspase-8 and FADD to trigger apoptosis and instead induces a Ca2+ response via docking of PLCgamma1 to the calcium-inducing domain (CID) within CD95. This signaling pathway induces accumulation of inflammatory Th17 cells in damaged organs of lupus patients, thereby aggravating disease pathology. A large-scale screen revealed that the HIV protease inhibitor ritonavir is a potent disruptor of the CD95-PLCgamma1 interaction. A structure-activity relationship approach highlighted that ritonavir is a peptidomimetic that shares structural characteristics with CID with respect to docking to PLCgamma1. Thus, we synthesized CID peptidomimetics abrogating both the CD95-driven Ca2+ response and transmigration of Th17 cells. Injection of ritonavir and the CID peptidomimetic into lupus mice alleviated clinical symptoms, opening a new avenue for the generation of drugs for lupus patients.
30429604	15	19	CD95	gene	CUI-less
30429604	20	29	PLCgamma1	gene	CUI-less
30429604	51	55	Th17	gene	CUI-less
30429604	77	82	CD95L	gene	CUI-less
30429604	110	117	m-CD95L	gene	CUI-less
30429604	138	154	metalloproteases	gene	CUI-less
30429604	184	191	s-CD95L	gene	CUI-less
30429604	201	208	m-CD95L	gene	CUI-less
30429604	230	237	s-CD95L	gene	CUI-less
30429604	242	246	CD95	gene	CUI-less
30429604	264	273	caspase-8	gene	CUI-less
30429604	278	282	FADD	gene	CUI-less
30429604	326	330	Ca2+	drug	CHEBI:29108|BERN:287734103
30429604	355	364	PLCgamma1	gene	CUI-less
30429604	372	379	calcium	drug	CHEBI:22984|BERN:4175403
30429604	409	413	CD95	gene	CUI-less
30429604	507	512	lupus	disease	BERN:256340901
30429604	601	613	HIV protease	gene	CUI-less
30429604	601	604	HIV	species	NCBI:txid12721
30429604	624	633	ritonavir	drug	MESH:D019438|BERN:4225903
30429604	663	667	CD95	gene	CUI-less
30429604	668	677	PLCgamma1	gene	CUI-less
30429604	751	760	ritonavir	drug	MESH:D019438|BERN:4225903
30429604	856	865	PLCgamma1	gene	CUI-less
30429604	928	932	CD95	gene	CUI-less
30429604	940	944	Ca2+	drug	CHEBI:29108|BERN:287734103
30429604	1001	1010	ritonavir	drug	MESH:D019438|BERN:4225903
30429604	1043	1048	lupus	disease	BERN:256340901
30429604	1049	1053	mice	species	NCBI:txid10095
30429604	1137	1142	lupus	disease	BERN:256340901
```

**Comment by amalic** [comment]
Same result when running on port 8008. Maybe your docker installation or network config is not allowing access to external services.

**Comment by shipse92** [comment]
My result same with you.

Focus on gene ID. Drug, disease, species has IDs. But, Gene is all CUI-less.
You can find error message like this if you see your nohup_gene.out.

`java.io.IOException: Cannot run program "./Ab3P": error=13, Permission denied
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at java.lang.Runtime.exec(Runtime.java:620)
at java.lang.Runtime.exec(Runtime.java:450)
at java.lang.Runtime.exec(Runtime.java:347)
at GNormPluslib.GNR.LoadInputFile(GNR.java:72)
at GNormPluslib.GNormPlus.run(GNormPlus.java:315)
at GNormPluslib.GNormPlusServer.main(GNormPlusServer.java:35)
Caused by: java.io.IOException: error=13, Permission denied
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 6 more`

**Comment by shipse92** [comment]
Oh, I did it.
call this
http://localhost:8008/?pmid=30429604&format=pubtator

result is 
```
30429604|t|Disrupting the CD95-PLCgamma1 interaction prevents Th17-driven inflammation.
30429604|a|CD95L is a transmembrane ligand (m-CD95L) that is cleaved by metalloproteases to release a soluble ligand (s-CD95L). Unlike m-CD95L, interaction between s-CD95L and CD95 fails to recruit caspase-8 and FADD to trigger apoptosis and instead induces a Ca2+ response via docking of PLCgamma1 to the calcium-inducing domain (CID) within CD95. This signaling pathway induces accumulation of inflammatory Th17 cells in damaged organs of lupus patients, thereby aggravating disease pathology. A large-scale screen revealed that the HIV protease inhibitor ritonavir is a potent disruptor of the CD95-PLCgamma1 interaction. A structure-activity relationship approach highlighted that ritonavir is a peptidomimetic that shares structural characteristics with CID with respect to docking to PLCgamma1. Thus, we synthesized CID peptidomimetics abrogating both the CD95-driven Ca2+ response and transmigration of Th17 cells. Injection of ritonavir and the CID peptidomimetic into lupus mice alleviated clinical symptoms, opening a new avenue for the generation of drugs for lupus patients.
30429604	15	19	CD95	gene	MIM:134637|HGNC:11920|Ensembl:ENSG00000026103|BERN:323737202
30429604	20	29	PLCgamma1	gene	MIM:172420|HGNC:9065|Ensembl:ENSG00000124181|BERN:324301002
30429604	51	55	Th17	gene	BERN:326428902
30429604	77	82	CD95L	gene	MIM:134638|HGNC:11936|Ensembl:ENSG00000117560|BERN:323738202
30429604	110	117	m-CD95L	gene	CUI-less
30429604	138	154	metalloproteases	gene	CUI-less
30429604	184	191	s-CD95L	gene	CUI-less
30429604	201	208	m-CD95L	gene	CUI-less
30429604	230	237	s-CD95L	gene	CUI-less
30429604	242	246	CD95	gene	MIM:134637|HGNC:11920|Ensembl:ENSG00000026103|BERN:323737202
30429604	264	273	caspase-8	gene	MIM:601763|HGNC:1509|Ensembl:ENSG00000064012|BERN:325295202
30429604	278	282	FADD	gene	MIM:602457|HGNC:3573|Ensembl:ENSG00000168040|BERN:325389602
30429604	326	330	Ca2+	drug	CHEBI:29108|BERN:287734103
30429604	355	364	PLCgamma1	gene	MIM:172420|HGNC:9065|Ensembl:ENSG00000124181|BERN:324301002
30429604	372	379	calcium	drug	CHEBI:22984|BERN:4175403
30429604	409	413	CD95	gene	MIM:134637|HGNC:11920|Ensembl:ENSG00000026103|BERN:323737202
30429604	507	512	lupus	disease	BERN:256340901
30429604	601	604	HIV	species	NCBI:txid12721
30429604	601	613	HIV protease	gene	CUI-less
30429604	624	633	ritonavir	drug	MESH:D019438|BERN:4225903
30429604	663	667	CD95	gene	MIM:134637|HGNC:11920|Ensembl:ENSG00000026103|BERN:323737202
30429604	668	677	PLCgamma1	gene	MIM:172420|HGNC:9065|Ensembl:ENSG00000124181|BERN:324301002
30429604	751	760	ritonavir	drug	MESH:D019438|BERN:4225903
30429604	856	865	PLCgamma1	gene	MIM:172420|HGNC:9065|Ensembl:ENSG00000124181|BERN:324301002
30429604	928	932	CD95	gene	MIM:134637|HGNC:11920|Ensembl:ENSG00000026103|BERN:323737202
30429604	940	944	Ca2+	drug	CHEBI:29108|BERN:287734103
30429604	1001	1010	ritonavir	drug	MESH:D019438|BERN:4225903
30429604	1043	1048	lupus	disease	BERN:256340901
30429604	1049	1053	mice	species	NCBI:txid10095
30429604	1137	1142	lupus	disease	BERN:256340901
```


Gene ID is come back now.

Permission was wrong.

resources/normalizers/gene/CRF/crf_test
resources/normalizers/gene/Ab3P

Two files must have executable permission.

Fine. 
It works!
Thank you.

**Comment by shipse92** [comment]
Now this issue closing myself.
Thankyou
